
export const START_CONVERSATION = 'FC_START_CONVERSATION';

export const TOGGLE_MAIN_WINDOW = 'FC_TOGGLE_MAIN_WINDOW';
export const CONVERSATIONS_SAMPLE_ACTION = 'CONVERSATIONS_SAMPLE_ACTION';
export const CONVERSATION_SAMPLE_ACTION = 'CONVERSATION_SAMPLE_ACTION';

export const GET_USER_START = 'FC_GET_USER_START';
export const GET_USER_END = 'FC_GET_USER_END';

export const GET_CONTACTS_START = 'FC_GET_CONTACTS_START';
export const GET_CONTACTS_END = 'FC_GET_CONTACTS_END';